name: "Run experiments with JarvisLabs and W&B"
description: "Run experiments with JarvisLabs and W&B"
inputs:
  CUR_BRANCH:
    required: true
  CUR_PR_ID:
    required: true
  GDRIVE_CREDENTIAL:
    required: true
  GH_ACCESS_TOKEN:
    required: true
  JARVISLABS_ID:
    required: true
  JARVISLABS_ACCESS_TOKEN:
    required: true
  WANDB_PROJECT:
    required: true
  WANDB_API_KEY:
    required: true
runs:
  using: "composite"
  steps:
      - name: prepare script
        env:
          CUR_BRANCH: ${{ inputs.CUR_BRANCH }}
          CUR_PR_ID: ${{ inputs.CUR_PR_ID }}
          GDRIVE_CREDENTIAL: ${{ inputs.GDRIVE_CREDENTIAL }}
          GH_ACCESS_TOKEN: ${{ inputs.GH_ACCESS_TOKEN }}
          CLOUD_ID: ${{ inputs.JARVISLABS_ID }}
          CLOUD_AT: ${{ inputs.JARVISLABS_ACCESS_TOKEN }}
          WANDB_PROJECT: ${{ inputs.WANDB_PROJECT }}
          WANDB_API_KEY: ${{ inputs.WANDB_API_KEY }}
        run: |
          envsubst \
            '$CUR_BRANCH, \
             $CUR_PR_ID, \
             $GDRIVE_CREDENTIAL, \
             $GH_ACCESS_TOKEN, \
             $CLOUD_ID, \
             $CLOUD_AT, \
             $WANDB_PROJECT, \
             $WANDB_API_KEY' \
             < scripts/jl_exp_wandb.sh \
             > scripts/jl_exp_wandb_tmp.sh
        shell: bash             
             
      - name: install jarvislabs client
        run: |
          pip install typer
          pip install git+https://github.com/jarvislabsai/jlclient.git
        shell: bash          
          
      - name: add script to jarvislabs
        id: add_script
        run: |
          python clouds/jarvislabs.py \
            script add \
              ${{ inputs.JARVISLABS_ACCESS_TOKEN }} ${{ inputs.JARVISLABS_ID }} scripts/jl_exp_wandb_tmp.sh \
                > outputs.txt
          echo "::set-output name=script_id::$(cat outputs.txt)"
        shell: bash          
          
      - name: create vm on jarvislabs
        run: |
          python clouds/jarvislabs.py \
            vm create \
              ${{ inputs.JARVISLABS_ACCESS_TOKEN }} ${{ inputs.JARVISLABS_ID }} ${{ steps.add_script.outputs.script_id }}
        shell: bash              
              
      - name: remove script from jarvislabs
        run: |
          python clouds/jarvislabs.py \
            script remove \
              ${{ inputs.JARVISLABS_ACCESS_TOKEN }} ${{ inputs.JARVISLABS_ID }} ${{ steps.add_script.outputs.script_id }}
        shell: bash              
